### ISSUE TITLE
failed to build with conan version 2.0.16

### ISSUE THREAD

**Issue by mountain** [hbatagelo/impvis#1]
Thanks for your cool contribution for this software.

I am a newbie of C++ programming, and I installed conan via pip, and 

```bash
conan version
```

gives information:
* version: 2.0.16
* python
  * version: 3.10.2
  * sys_version: 3.10.2 (main, Mar  3 2022, 15:54:57) [Clang 13.0.0 (clang-1300.0.29.30)]

And when I followed the construction on the README, I met the error

```bash
mkdir build && cd build
BUILD_TYPE=Release
cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- List of sanitizers: address,undefined
-- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
CMake Error at cmake/Conan.cmake:26 (conan_check):
  Unknown CMake command "conan_check".
Call Stack (most recent call first):
  cmake/Common.cmake:124 (run_conan)
  CMakeLists.txt:5 (include)
```

And I guess it is because the conan version is not correct?

**Comment by hbatagelo** [comment]
Thank you for filing this issue.

Impvis uses a CMake-Conan wrapper that is not compatible with Conan 2. For now, use an earlier version:

```sh
pip install 'conan>=1.0,<2.0'
```

Additionally, although it's not directly related to this problem, I've noticed that you are building for macOS. If you encounter problems running the shaders on macOS, you may need to change the `#version` directives in the shaders, from `#version 330 es` to `#version 410`.

**Comment by mountain** [comment]
Thank you for your answer, and merry Christmas!
